[project]
name = "engenharia-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Matheuszy", email = "matheusalmeidacarlos@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.142.2",
    "numpy>=2.5.3",
    "openai>=3.26.0",
    "opencv-python>=5.0.0.93",
    "python-dotenv>=1.2.4",
    "python-multipart>=0.0.32",
    "uvicorn>=0.54.0",
]

[project.scripts]
engenharia-service = "engenharia_service:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
